config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :transactions, only: [:index, :show, :create]

  get "/monzo/fetch", to: "authentications#fetch", as: :monzo_fetch
  get "/monzo/callback", to: "authentications#callback", as: :monzo_callback
  get "/monzo/refresh", to: "authentications#refresh", as: :monzo_refresh

  resources :authentications, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user

  validates :currency, inclusion: { in: %w(GBP EUR USD) }

  monetize :amount_cents

  def self.to_csv
    attributes = %w{description amount account category settled notes}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.find_each do |transaction|
        csv << attributes.map { |a| transaction.send(a) }
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  def fetch
    client_id = ENV['MONZO_CLIENT_ID']
    state_token = ENV['STATE_TOKEN'] # (0...8).map { (65 + rand(26)).chr }.join
    redirect_uri = 'http://localhost:3000/monzo/callback'

    url = "https://auth.monzo.com/?redirect_uri=#{redirect_uri}&client_id=#{client_id}&&response_type=code&state=#{state_token}"

    redirect_to url
  end

  def callback
    url = "https://api.monzo.com/oauth2/token"
    redirect_uri = 'http://localhost:3000/monzo/callback'

    body = {
      "grant_type"=> "authorization_code",
      "client_id"=> ENV['MONZO_CLIENT_ID'],
      "client_secret"=> ENV['MONZO_CLIENT_SECRET'],
      "redirect_uri"=> redirect_uri,
      "code"=> params[:code]
    }

    response = Faraday.post(url, body)
    json_response = JSON.parse(response.body)

    update_user(json_response['access_token'], json_response['refresh_token'])

    flash[:notice] = 'You have successfully linked your Monzo account'
    redirect_to transactions_path
  end

  def index
    @user = current_user
    url = "https://api.monzo.com/accounts"

    body = {"Authorization" => @user.monzo_access_token}

    response = Faraday.get(url, body)
    json_response = JSON.parse(response.body)
    binding.pry
  end

  def refresh

    url = "https://api.monzo.com/oauth2/token"

    body = {
      "grant_type"=> "refresh_token",
      "client_id"=> ENV['MONZO_CLIENT_ID'],
      "client_secret"=> ENV['MONZO_CLIENT_SECRET'],
      "refresh_token"=> current_user.monzo_refresh_token
    }

    json_response = JSON.parse(Faraday.post(url, body))

    update_user(json_response['access_token'], json_response['refresh_token'])

  end

  private

  def update_user(access_token, refresh_token)
    @user = current_user

    @user.update(
      monzo_access_token: access_token,
      monzo_refresh_token: refresh_token
    )
  end

  def import_from_monzo

    url = "https://api.monzo.com/transactions"

    body = {
      "Authorization" => "Bearer #{}",
      "account_id" => current_user
    }
    Faraday.get()




  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  def index
    @transactions = Transaction.where(user: current_user)

    respond_to do |format|
      format.html
      format.csv { send_data @transactions.to_csv, filename: "transactions-#{Date.today}.csv" }
    end
  end

  def show
    @transaction = Transaction.find(params[:id])
  end

  def create
    transaction = Transaction.new(transaction_params)
    transaction.user = current_user
  end

  def edit
  end

  private

  def transaction_params
   params.requre(:transaction).permit(:category, :account, :currency, :settled, :notes)
  end

  # def export_to_csv

  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authentications/callback.html.erb
<p><%= @response.body %></p>

app/views/authentications/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <% @accounts.each do |account| %>

      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spending Report</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div class="row">
    <div class="col text-center">
      <h1>Homepage</h1>
      <p>Sub-title</p>

      <%= link_to "See transactions", transactions_path, class: "btn btn-primary"%>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
<!--         <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li> -->
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/transactions/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <div class="title">
        <h1>All transactions</h1>
      </div>
      <div class="links text-right">
        <%= link_to "Export to CSV", transactions_path(format: :csv) %>
        <%= link_to 'Link to Monzo', monzo_fetch_path %>
        <%= link_to 'View Monzo accounts', authentications_path %>
      </div>
      <div class="list-transaction">
        <% @transactions.each do |transaction| %>
          <%= link_to transaction_path(transaction) do %>
            <div class="card-transaction">
              <img src="/" alt="<%= transaction.account %>">
              <div class="card-transaction-infos">
                <h2><%= transaction.description %></h2>
                <p><%= humanized_money_with_symbol(transaction.amount) %></p>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/transactions/show.html.erb
<div class="container">
  <div class="row">
    <div class="col" style="padding: 15px 0;">
      <%= link_to "All transactions", transactions_path %>
    </div>
  </div>
  <div class="row">
    <div class="col text-center">
      <h2 style="padding: 20px 0;"><%= @transaction.description %></h2>
      <p><strong>Category:</strong> <%= @transaction.category %></p>
      <p><strong>Amount:</strong> <%= humanized_money_with_symbol(@transaction.amount)  %></p>
      <p><strong>Account:</strong> <%= @transaction.account %></p>
      <p><strong>Currency:</strong> <%= @transaction.currency %></p>
      <p><strong>Settled:</strong> <%= @transaction.settled.strftime('%e/%m/%y %H:%M') %></p>
      <p><strong>Notes:</strong> <%= @transaction.notes %></p>
    </div>
  </div>
</div>